/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ChartTestRouteImport } from './routes/chart-test'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TerminalRouteImport } from './routes/_terminal'
import { Route as TerminalIndexRouteImport } from './routes/_terminal/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as TerminalWorkspaceStoreRouteImport } from './routes/_terminal/workspace-store'
import { Route as TerminalWorkflowsRouteImport } from './routes/_terminal/workflows'
import { Route as TerminalPluginsRouteImport } from './routes/_terminal/plugins'
import { Route as TerminalNotificationsRouteImport } from './routes/_terminal/notifications'
import { Route as TerminalIndicatorsRouteImport } from './routes/_terminal/indicators'
import { Route as TerminalBotsRouteImport } from './routes/_terminal/bots'
import { Route as TerminalAccountsRouteImport } from './routes/_terminal/accounts'
import { Route as TerminalWorkspaceWorkspaceIdRouteImport } from './routes/_terminal/workspace/$workspaceId'
import { Route as TerminalPairPairRouteImport } from './routes/_terminal/pair/$pair'
import { Route as TerminalClsMarketIdRouteImport } from './routes/_terminal/$cls/$market/$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartTestRoute = ChartTestRouteImport.update({
  id: '/chart-test',
  path: '/chart-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/_terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalIndexRoute = TerminalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalWorkspaceStoreRoute = TerminalWorkspaceStoreRouteImport.update({
  id: '/workspace-store',
  path: '/workspace-store',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalWorkflowsRoute = TerminalWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalPluginsRoute = TerminalPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalNotificationsRoute = TerminalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalIndicatorsRoute = TerminalIndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalBotsRoute = TerminalBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalAccountsRoute = TerminalAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalWorkspaceWorkspaceIdRoute =
  TerminalWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => TerminalRoute,
  } as any)
const TerminalPairPairRoute = TerminalPairPairRouteImport.update({
  id: '/pair/$pair',
  path: '/pair/$pair',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalClsMarketIdRoute = TerminalClsMarketIdRouteImport.update({
  id: '/$cls/$market/$id',
  path: '/$cls/$market/$id',
  getParentRoute: () => TerminalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TerminalIndexRoute
  '/admin': typeof AdminRoute
  '/chart-test': typeof ChartTestRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/accounts': typeof TerminalAccountsRoute
  '/bots': typeof TerminalBotsRoute
  '/indicators': typeof TerminalIndicatorsRoute
  '/notifications': typeof TerminalNotificationsRoute
  '/plugins': typeof TerminalPluginsRoute
  '/workflows': typeof TerminalWorkflowsRoute
  '/workspace-store': typeof TerminalWorkspaceStoreRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/pair/$pair': typeof TerminalPairPairRoute
  '/workspace/$workspaceId': typeof TerminalWorkspaceWorkspaceIdRoute
  '/$cls/$market/$id': typeof TerminalClsMarketIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/chart-test': typeof ChartTestRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/accounts': typeof TerminalAccountsRoute
  '/bots': typeof TerminalBotsRoute
  '/indicators': typeof TerminalIndicatorsRoute
  '/notifications': typeof TerminalNotificationsRoute
  '/plugins': typeof TerminalPluginsRoute
  '/workflows': typeof TerminalWorkflowsRoute
  '/workspace-store': typeof TerminalWorkspaceStoreRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/': typeof TerminalIndexRoute
  '/pair/$pair': typeof TerminalPairPairRoute
  '/workspace/$workspaceId': typeof TerminalWorkspaceWorkspaceIdRoute
  '/$cls/$market/$id': typeof TerminalClsMarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_terminal': typeof TerminalRouteWithChildren
  '/admin': typeof AdminRoute
  '/chart-test': typeof ChartTestRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/_terminal/accounts': typeof TerminalAccountsRoute
  '/_terminal/bots': typeof TerminalBotsRoute
  '/_terminal/indicators': typeof TerminalIndicatorsRoute
  '/_terminal/notifications': typeof TerminalNotificationsRoute
  '/_terminal/plugins': typeof TerminalPluginsRoute
  '/_terminal/workflows': typeof TerminalWorkflowsRoute
  '/_terminal/workspace-store': typeof TerminalWorkspaceStoreRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/_terminal/': typeof TerminalIndexRoute
  '/_terminal/pair/$pair': typeof TerminalPairPairRoute
  '/_terminal/workspace/$workspaceId': typeof TerminalWorkspaceWorkspaceIdRoute
  '/_terminal/$cls/$market/$id': typeof TerminalClsMarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chart-test'
    | '/landing'
    | '/onboarding'
    | '/sign-in'
    | '/accounts'
    | '/bots'
    | '/indicators'
    | '/notifications'
    | '/plugins'
    | '/workflows'
    | '/workspace-store'
    | '/checkout/success'
    | '/pair/$pair'
    | '/workspace/$workspaceId'
    | '/$cls/$market/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/chart-test'
    | '/landing'
    | '/onboarding'
    | '/sign-in'
    | '/accounts'
    | '/bots'
    | '/indicators'
    | '/notifications'
    | '/plugins'
    | '/workflows'
    | '/workspace-store'
    | '/checkout/success'
    | '/'
    | '/pair/$pair'
    | '/workspace/$workspaceId'
    | '/$cls/$market/$id'
  id:
    | '__root__'
    | '/_terminal'
    | '/admin'
    | '/chart-test'
    | '/landing'
    | '/onboarding'
    | '/sign-in'
    | '/_terminal/accounts'
    | '/_terminal/bots'
    | '/_terminal/indicators'
    | '/_terminal/notifications'
    | '/_terminal/plugins'
    | '/_terminal/workflows'
    | '/_terminal/workspace-store'
    | '/checkout/success'
    | '/_terminal/'
    | '/_terminal/pair/$pair'
    | '/_terminal/workspace/$workspaceId'
    | '/_terminal/$cls/$market/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TerminalRoute: typeof TerminalRouteWithChildren
  AdminRoute: typeof AdminRoute
  ChartTestRoute: typeof ChartTestRoute
  LandingRoute: typeof LandingRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-test': {
      id: '/chart-test'
      path: '/chart-test'
      fullPath: '/chart-test'
      preLoaderRoute: typeof ChartTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_terminal': {
      id: '/_terminal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_terminal/': {
      id: '/_terminal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TerminalIndexRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_terminal/workspace-store': {
      id: '/_terminal/workspace-store'
      path: '/workspace-store'
      fullPath: '/workspace-store'
      preLoaderRoute: typeof TerminalWorkspaceStoreRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/workflows': {
      id: '/_terminal/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof TerminalWorkflowsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/plugins': {
      id: '/_terminal/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof TerminalPluginsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/notifications': {
      id: '/_terminal/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof TerminalNotificationsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/indicators': {
      id: '/_terminal/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof TerminalIndicatorsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/bots': {
      id: '/_terminal/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof TerminalBotsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/accounts': {
      id: '/_terminal/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof TerminalAccountsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/workspace/$workspaceId': {
      id: '/_terminal/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof TerminalWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/pair/$pair': {
      id: '/_terminal/pair/$pair'
      path: '/pair/$pair'
      fullPath: '/pair/$pair'
      preLoaderRoute: typeof TerminalPairPairRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/$cls/$market/$id': {
      id: '/_terminal/$cls/$market/$id'
      path: '/$cls/$market/$id'
      fullPath: '/$cls/$market/$id'
      preLoaderRoute: typeof TerminalClsMarketIdRouteImport
      parentRoute: typeof TerminalRoute
    }
  }
}

interface TerminalRouteChildren {
  TerminalAccountsRoute: typeof TerminalAccountsRoute
  TerminalBotsRoute: typeof TerminalBotsRoute
  TerminalIndicatorsRoute: typeof TerminalIndicatorsRoute
  TerminalNotificationsRoute: typeof TerminalNotificationsRoute
  TerminalPluginsRoute: typeof TerminalPluginsRoute
  TerminalWorkflowsRoute: typeof TerminalWorkflowsRoute
  TerminalWorkspaceStoreRoute: typeof TerminalWorkspaceStoreRoute
  TerminalIndexRoute: typeof TerminalIndexRoute
  TerminalPairPairRoute: typeof TerminalPairPairRoute
  TerminalWorkspaceWorkspaceIdRoute: typeof TerminalWorkspaceWorkspaceIdRoute
  TerminalClsMarketIdRoute: typeof TerminalClsMarketIdRoute
}

const TerminalRouteChildren: TerminalRouteChildren = {
  TerminalAccountsRoute: TerminalAccountsRoute,
  TerminalBotsRoute: TerminalBotsRoute,
  TerminalIndicatorsRoute: TerminalIndicatorsRoute,
  TerminalNotificationsRoute: TerminalNotificationsRoute,
  TerminalPluginsRoute: TerminalPluginsRoute,
  TerminalWorkflowsRoute: TerminalWorkflowsRoute,
  TerminalWorkspaceStoreRoute: TerminalWorkspaceStoreRoute,
  TerminalIndexRoute: TerminalIndexRoute,
  TerminalPairPairRoute: TerminalPairPairRoute,
  TerminalWorkspaceWorkspaceIdRoute: TerminalWorkspaceWorkspaceIdRoute,
  TerminalClsMarketIdRoute: TerminalClsMarketIdRoute,
}

const TerminalRouteWithChildren = TerminalRoute._addFileChildren(
  TerminalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TerminalRoute: TerminalRouteWithChildren,
  AdminRoute: AdminRoute,
  ChartTestRoute: ChartTestRoute,
  LandingRoute: LandingRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
