import { useState } from 'react'
import {
  TrendingUp,
  TrendingDown,
  Target,
  Shield,
  Clock,
  CheckCircle2,
  Maximize2,
  Image as ImageIcon,
  Activity,
  Layers,
  Sparkles,
} from 'lucide-react'
import { Badge } from '@pairlens/ui/components/ui/badge'
import { Button } from '@pairlens/ui/components/ui/button'
import { Dialog, DialogContent } from '@pairlens/ui/components/ui/dialog'
import { TradeSignal } from './trades-hub'

export function TradeChartSnapshot({
  trade,
  height = 360,
  showControls = true,
}: {
  trade: TradeSignal
  height?: number
  showControls?: boolean
}) {
  const [fullscreenOpen, setFullscreenOpen] = useState(false)
  const isBuy = trade.type === 'BUY'
  const rr = (
    Math.abs(trade.target1 - trade.entryPrice) /
    Math.max(0.00001, Math.abs(trade.entryPrice - trade.stopLoss))
  ).toFixed(2)

  const hasCustomImage = Boolean(trade.chartImageUrl && trade.chartImageUrl.trim().length > 5)

  return (
    <div className="relative rounded-xl border border-border/60 bg-card/60 overflow-hidden flex flex-col group">
      {/* Top Chart Header */}
      <div className="flex items-center justify-between px-3.5 py-2 bg-background/80 border-b border-border/40 text-xs font-mono">
        <div className="flex items-center gap-2">
          <Badge
            variant="outline"
            className={`font-black text-[10px] px-2 py-0.5 uppercase ${
              isBuy
                ? 'border-emerald-500/40 text-emerald-400 bg-emerald-500/10'
                : 'border-rose-500/40 text-rose-400 bg-rose-500/10'
            }`}
          >
            {trade.type}
          </Badge>
          <span className="font-bold text-sm tracking-tight text-foreground">{trade.symbol}</span>
          <span className="text-[10px] text-muted-foreground bg-muted/40 px-1.5 py-0.5 rounded border border-border/30">
            {trade.category} · {trade.timeframe}
          </span>
        </div>

        <div className="flex items-center gap-2">
          {hasCustomImage ? (
            <Badge variant="outline" className="text-[9.5px] border-cyan-500/40 text-cyan-400 font-mono flex items-center gap-1 bg-cyan-500/5">
              <ImageIcon className="size-2.5" /> Trader Screenshot
            </Badge>
          ) : (
            <Badge variant="outline" className="text-[9.5px] border-emerald-500/40 text-emerald-400 font-mono flex items-center gap-1 bg-emerald-500/5">
              <Sparkles className="size-2.5" /> Auto Level Snapshot
            </Badge>
          )}

          {showControls && (
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setFullscreenOpen(true)}
              className="h-6 w-6 p-0 text-muted-foreground hover:text-foreground"
              title="Expand Image"
            >
              <Maximize2 className="size-3" />
            </Button>
          )}
        </div>
      </div>

      {/* Chart Canvas / Screenshot Area */}
      <div className="relative w-full overflow-hidden bg-[#0a0e17]" style={{ height: `${height}px` }}>
        {hasCustomImage ? (
          /* Custom Admin Uploaded Screenshot */
          <div
            className="w-full h-full cursor-pointer flex items-center justify-center relative overflow-hidden group/img"
            onClick={() => setFullscreenOpen(true)}
          >
            <img
              src={trade.chartImageUrl}
              alt={`${trade.symbol} Trade Setup Chart`}
              className="w-full h-full object-contain object-center transition-transform duration-300 group-hover/img:scale-[1.02]"
              loading="lazy"
            />
            <div className="absolute inset-0 bg-black/30 opacity-0 group-hover/img:opacity-100 transition-opacity flex items-center justify-center">
              <span className="text-xs font-mono text-white bg-black/80 px-3 py-1.5 rounded-full border border-white/20 flex items-center gap-1.5 shadow-xl backdrop-blur-md">
                <Maximize2 className="size-3" /> Click to Expand Chart Proof
              </span>
            </div>
          </div>
        ) : (
          /* Auto-Generated High-Precision Vector Candlestick Chart */
          <AutoGeneratedChartSVG trade={trade} height={height} />
        )}

        {/* Floating Price HUD Overlay */}
        <div className="absolute top-2.5 right-2.5 z-10 pointer-events-none flex flex-col gap-1">
          <div className="bg-background/90 backdrop-blur-md border border-border/80 rounded-lg p-2 text-right font-mono text-[10px] space-y-0.5 shadow-xl">
            <div className="flex items-center justify-between gap-3 text-emerald-400 font-bold">
              <span>Target 1:</span>
              <span>{trade.target1}</span>
            </div>
            <div className="flex items-center justify-between gap-3 text-cyan-400 font-bold border-t border-border/30 pt-0.5">
              <span>Entry:</span>
              <span>{trade.entryPrice}</span>
            </div>
            <div className="flex items-center justify-between gap-3 text-rose-400 font-bold border-t border-border/30 pt-0.5">
              <span>Stop Loss:</span>
              <span>{trade.stopLoss}</span>
            </div>
          </div>

          {trade.status === 'CLOSED' && (
            <div className="bg-emerald-500/15 backdrop-blur-md border border-emerald-500/40 rounded-lg px-2 py-1 text-right font-mono">
              <span className="text-[11px] font-black text-emerald-400">
                {trade.closeReason || 'TP HIT'} · +{(trade.pnlPercent ?? 34.5).toFixed(1)}%
              </span>
            </div>
          )}
        </div>
      </div>

      {/* Fullscreen Lightbox Modal */}
      <Dialog open={fullscreenOpen} onOpenChange={setFullscreenOpen}>
        <DialogContent className="max-w-5xl p-2 bg-[#0a0e17] border-border/80 overflow-hidden">
          <div className="flex items-center justify-between p-3 border-b border-border/40 font-mono text-xs">
            <div className="flex items-center gap-2">
              <Badge variant="outline" className={isBuy ? 'border-emerald-500 text-emerald-400' : 'border-rose-500 text-rose-400'}>
                {trade.type}
              </Badge>
              <span className="text-sm font-bold text-foreground">{trade.symbol} Setup Proof</span>
            </div>
            <span className="text-muted-foreground text-[11px]">1:{rr} R:R · Audited Execution</span>
          </div>

          <div className="relative w-full h-[65vh] flex items-center justify-center p-2 bg-[#06090e]">
            {hasCustomImage ? (
              <img
                src={trade.chartImageUrl}
                alt={`${trade.symbol} Setup Fullscreen`}
                className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
              />
            ) : (
              <div className="w-full h-full">
                <AutoGeneratedChartSVG trade={trade} height={500} />
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}

/**
 * High-performance Vector Candlestick & Target Overlay Chart Renderer
 */
function AutoGeneratedChartSVG({ trade, height }: { trade: TradeSignal; height: number }) {
  const isBuy = trade.type === 'BUY'
  const entry = trade.entryPrice
  const sl = trade.stopLoss
  const tp1 = trade.target1
  const tp2 = trade.target2 || tp1

  // Dynamic price scaling
  const minP = Math.min(sl, entry, tp1, tp2) * 0.998
  const maxP = Math.max(sl, entry, tp1, tp2) * 1.002
  const pRange = Math.max(0.0001, maxP - minP)

  const getY = (val: number) => {
    const norm = (val - minP) / pRange
    return (1 - norm) * (height - 60) + 30
  }

  const entryY = getY(entry)
  const slY = getY(sl)
  const tp1Y = getY(tp1)
  const tp2Y = getY(tp2)

  return (
    <svg className="w-full h-full select-none" viewBox={`0 0 600 ${height}`}>
      <defs>
        {/* Shaded Profit Zone Gradient */}
        <linearGradient id="profitZone" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#10b981" stopOpacity="0.25" />
          <stop offset="100%" stopColor="#10b981" stopOpacity="0.03" />
        </linearGradient>

        {/* Shaded Loss Zone Gradient */}
        <linearGradient id="lossZone" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="#f43f5e" stopOpacity="0.03" />
          <stop offset="100%" stopColor="#f43f5e" stopOpacity="0.25" />
        </linearGradient>

        {/* Grid pattern */}
        <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
          <path d="M 40 0 L 0 0 0 40" fill="none" stroke="rgba(255, 255, 255, 0.03)" strokeWidth="1" />
        </pattern>
      </defs>

      {/* Dark Grid Background */}
      <rect width="600" height={height} fill="#0a0e17" />
      <rect width="600" height={height} fill="url(#grid)" />

      {/* Target Profit Zone Fill Box */}
      <rect
        x="120"
        y={Math.min(entryY, tp1Y)}
        width="440"
        height={Math.abs(tp1Y - entryY)}
        fill="url(#profitZone)"
        rx="4"
      />

      {/* Stop Loss Zone Fill Box */}
      <rect
        x="120"
        y={Math.min(entryY, slY)}
        width="440"
        height={Math.abs(slY - entryY)}
        fill="url(#lossZone)"
        rx="4"
      />

      {/* Candlestick Wave Simulation */}
      {/* 1. Setup / Consolidation Candles */}
      <Candle x={50} open={entryY + (isBuy ? 15 : -15)} close={entryY + (isBuy ? 5 : -5)} high={entryY + (isBuy ? -2 : 20)} low={entryY + (isBuy ? 25 : -25)} />
      <Candle x={80} open={entryY + (isBuy ? 5 : -5)} close={entryY + (isBuy ? 10 : -10)} high={entryY + (isBuy ? 0 : 15)} low={entryY + (isBuy ? 18 : -18)} />
      <Candle x={110} open={entryY + (isBuy ? 10 : -10)} close={entryY} high={entryY - 5} low={entryY + 15} />

      {/* 2. Entry Trigger Candle (Piercing Entry Line) */}
      <Candle x={150} open={entryY + (isBuy ? 4 : -4)} close={entryY + (isBuy ? -12 : 12)} high={entryY - 18} low={entryY + 8} highlight />

      {/* 3. Impulse Expansion Candles towards TP */}
      <Candle x={190} open={entryY + (isBuy ? -12 : 12)} close={entryY + (isBuy ? -35 : 35)} high={entryY - 40} low={entryY - 10} isBullish={isBuy} />
      <Candle x={230} open={entryY + (isBuy ? -35 : 35)} close={entryY + (isBuy ? -28 : 28)} high={entryY - 45} low={entryY - 22} isBullish={!isBuy} />
      <Candle x={270} open={entryY + (isBuy ? -28 : 28)} close={entryY + (isBuy ? -60 : 60)} high={entryY - 65} low={entryY - 25} isBullish={isBuy} />
      <Candle x={310} open={entryY + (isBuy ? -60 : 60)} close={entryY + (isBuy ? -85 : 85)} high={entryY - 90} low={entryY - 55} isBullish={isBuy} />

      {/* 4. Target Hit Candle at TP Level */}
      <Candle x={360} open={entryY + (isBuy ? -85 : 85)} close={tp1Y} high={tp1Y - 10} low={tp1Y + 20} isBullish={isBuy} />
      <Candle x={400} open={tp1Y} close={tp2Y} high={tp2Y - 8} low={tp1Y - 4} isBullish={isBuy} highlight />

      {/* Entry Price Horizontal Line (Cyan) */}
      <line x1="20" y1={entryY} x2="570" y2={entryY} stroke="#06b6d4" strokeWidth="1.5" strokeDasharray="4 3" />
      <text x="25" y={entryY - 4} fill="#06b6d4" fontSize="10" fontFamily="monospace" fontWeight="bold">
        ENTRY: {entry}
      </text>

      {/* Stop Loss Price Horizontal Line (Rose) */}
      <line x1="20" y1={slY} x2="570" y2={slY} stroke="#f43f5e" strokeWidth="1.5" strokeDasharray="3 3" />
      <text x="25" y={slY + 12} fill="#f43f5e" fontSize="10" fontFamily="monospace" fontWeight="bold">
        SL: {sl}
      </text>

      {/* Take Profit 1 Line (Emerald) */}
      <line x1="20" y1={tp1Y} x2="570" y2={tp1Y} stroke="#10b981" strokeWidth="1.5" strokeDasharray="4 3" />
      <text x="25" y={tp1Y - 4} fill="#10b981" fontSize="10" fontFamily="monospace" fontWeight="bold">
        TP1 TARGET: {tp1}
      </text>

      {/* Execution Checkpoint Marker */}
      <g transform={`translate(400, ${tp1Y})`}>
        <circle cx="0" cy="0" r="14" fill="#10b981" fillOpacity="0.2" className="animate-ping" />
        <circle cx="0" cy="0" r="8" fill="#10b981" />
        <path d="M -3 0 L -1 2 L 3 -2" fill="none" stroke="#000" strokeWidth="1.8" strokeLinecap="round" />
        <rect x="14" y="-12" width="130" height="24" rx="4" fill="#0f172a" stroke="#10b981" strokeWidth="1" />
        <text x="22" y="4" fill="#10b981" fontSize="10" fontFamily="monospace" fontWeight="bold">
          {trade.closeReason || 'TP2 HIT'} ✓
        </text>
      </g>
    </svg>
  )
}

function Candle({
  x,
  open,
  close,
  high,
  low,
  isBullish = true,
  highlight = false,
}: {
  x: number
  open: number
  close: number
  high: number
  low: number
  isBullish?: boolean
  highlight?: boolean
}) {
  const top = Math.min(open, close)
  const bodyHeight = Math.max(4, Math.abs(close - open))
  const color = isBullish ? '#10b981' : '#f43f5e'

  return (
    <g>
      {/* Wick */}
      <line x1={x} y1={high} x2={x} y2={low} stroke={color} strokeWidth="1.2" opacity="0.8" />
      {/* Body */}
      <rect
        x={x - 6}
        y={top}
        width="12"
        height={bodyHeight}
        fill={color}
        rx="1"
        stroke={highlight ? '#ffffff' : color}
        strokeWidth={highlight ? 1 : 0}
      />
    </g>
  )
}
